# Generated by Django 4.0.3 on 2022-04-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('archived', models.BooleanField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('task_list_type', models.TextField(choices=[('BL', 'backlog'), ('SP', 'sprint')], default='SP', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('workload', models.TextField(choices=[('S1', 'small (1)'), ('S2', 'small (2)'), ('S3', 'small (3)'), ('S5', 'small (5)'), ('M8', 'medium (8)'), ('M13', 'medium (13)'), ('M21', 'medium (21)'), ('L34', 'large (34)'), ('L55', 'large (55)'), ('L89', 'large (89)'), ('E144', 'epic (144)')], max_length=4)),
                ('status', models.TextField(choices=[('TD', 'to do'), ('IP', 'in progress'), ('RV', 'in review'), ('DO', 'done')], max_length=2)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.tasklist')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
