# Generated by Django 4.0.3 on 2022-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='RequirementPriority',
        ),
    ]
