# Generated by Django 4.0.3 on 2022-04-13 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_alter_tasklist_end_date_alter_tasklist_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 13, 49, 43, 72639, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
