# Generated by Django 4.0.3 on 2022-04-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_requirementstatus_alter_requirement_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('observation', models.TextField(blank=True)),
                ('priority', models.IntegerField()),
                ('placement', models.SmallIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.project')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.task')),
            ],
        ),
        migrations.RenameModel(
            old_name='RequirementStatus',
            new_name='TaskStatusName',
        ),
        migrations.RenameModel(
            old_name='RequirementWorkload',
            new_name='TaskWorkEstimate',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.AddField(
            model_name='taskstatusupdatehistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.taskstatusname'),
        ),
        migrations.AddField(
            model_name='taskstatusupdatehistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.developer'),
        ),
        migrations.AddField(
            model_name='task',
            name='workload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.taskworkestimate'),
        ),
    ]
