# Generated by Django 4.0.3 on 2022-04-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_task_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='workload',
            field=models.TextField(choices=[('S1', 'small (1)'), ('S2', 'small (2)'), ('S3', 'small (3)'), ('S5', 'small (5)'), ('M8', 'medium (8)'), ('M13', 'medium (13)'), ('M21', 'medium (21)'), ('L34', 'large (34)'), ('L55', 'large (55)'), ('L89', 'large (89)'), ('E144', 'epic (144)'), ('E233', 'epic (233)'), ('E377', 'epic (377)')], max_length=4),
        ),
    ]
