# Generated by Django 4.0.3 on 2022-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_task_duration_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='feeling',
            field=models.TextField(choices=[('SB', 'SUPERB'), ('HP', 'HAPPY'), ('RE', 'REGULAR'), ('SD', 'SAD'), ('AG', 'ANGRY'), ('UN', 'UNDEFINED')], default='UN', max_length=2),
        ),
    ]
