# Generated by Django 4.0.3 on 2022-05-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_tasklist_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_list_type',
            field=models.TextField(choices=[('RT', 'routine'), ('BL', 'backlog'), ('SP', 'sprint')], default='SP', max_length=2),
        ),
    ]
