# Generated by Django 4.0.3 on 2022-12-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0012_tag_tasktag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
    ]
